### ISSUE TITLE
"make boss" button a bit unclear

### ISSUE THREAD

**Issue by Sagekur** [trichner/nemesis#4]
In EVE's fleet management window there is a function called "Make Boss" which actually gives the fleet boss role to someone else.  

In this tool, having a button with that title infers that function when it really only changes the WL Manager ownership.

I'm not sure that there is a IGB function for giving away fleet boss, if there is, in Incursions we usually do have the WL Manager be the fleet boss.

**Comment by Sagekur** [comment]
Perhaps title the button "Promote to WL Manager" or "Pass WL Manager"

**Comment by trichner** [comment]
There is no way to change the actual boss via IGB. Here's whats possible: https://wiki.eveonline.com/en/wiki/IGB_Javascript_Methods
